### ISSUE TITLE
Firebase 실시간 데이터베이스 밑작업

### ISSUE THREAD

**Issue by hatchling13** [GNUCS-2022-Capstone-Design-ShareRoutine/ShareRoutine#6]
# 개요
애플리케이션에 필요한 `Firebase` 관련 서비스에 대해 밑작업을 진행한다. 이 과정에는 `FIrebase`에 앱 등록, 협업 기능 설정, 테스트 데이터 추가 등이 포함된다.

**Comment by harry123492** [comment]
firebase 연동위해 build gradle 프로젝트 수준과 앱 수준에 연동위한 코드들을 넣었고, MainActivity에 firebase에 데이터가 잘 들어가는지 확인하기 위해 코드 넣었음
